Add vote up and vote down system
VicDosya/react-post pull request #12
Opened 2022-12-14 22:07 UTC by VicDosya

2022-12-14 22:09 UTC, VicDosya commented
The votes are done using VoteUp, VoteDown Schemas.
Counting the votes were used individually with .documentCount().
When user chooses to vote otherwise - the previous vote gets erased using .deleteOne().
If user already voted the same vote, he gets error message.

2022-12-15 16:46 UTC, 8o8inCodes requested changes

2022-12-15 16:46 UTC, 8o8inCodes commented on client/src/Components/PostPage.js
> +  };
You can merge these two functions together, instead of having 2 apis for voting, have one
Post .../votes
Body:
{ vote: 1 } // or -1 to downvote

And then in the server do a check if vote > 0, upvote, else downvote.
Also make sure to validate that the only values that can be accepted by the server is 1 or -1. Otherwise, return an error.

2022-12-15 16:46 UTC, 8o8inCodes commented on client/src/Components/PostPage.js
> +  };
And in frontend you just create a function handleVote(1) or handleVote(-1)
Or even better handleVoteUp will call handleVote(1)

2022-12-15 16:46 UTC, 8o8inCodes commented on server/Schemas/VoteDown.js
> +  },
The votedown and up schemas are the same, so better have 1 which is called "PostVoteSchema"

And instead of votes field, call it "vote", which will have only -1, 0 or 1 values, much easier and saves a lot of code.

2022-12-15 16:46 UTC, 8o8inCodes commented on server/api/post.js
> +      });
Once you will have only one Vote schema, You can count the votes that are higher than 0 and then lower than 0.

2022-12-15 16:46 UTC, 8o8inCodes commented on server/api/post.js
> +    res.send({ error: "Post is not found." });
So in this logic, you're fetching the post, then vote up, and vote down, every fetch is taking time.
And only after all of that you're checking if post exists or not. You can make this function run faster when there is an error, if you validate if post exists right after you fetch the post.

await post.find.....
if(!post) return res.send(errorbalablbal)

2022-12-16 11:51 UTC, 8o8inCodes requested changes

2022-12-16 11:51 UTC, 8o8inCodes commented on server/api/post.js
> +  const validVoteNum = req.body.vote === 1 || req.body.vote === -1;
Since this validation takes almost no time at all, would be best to move it to the top of the function. 
if(req.body.vote !== 1 && req.body.vote !== -1) {
 return res.send(errorblabablaba)
}

Do the same with alreadyVoted, have the actual logic happen after all of these validations.

2022-12-16 12:32 UTC, 8o8inCodes requested changes

2022-12-16 12:32 UTC, 8o8inCodes commented on server/api/post.js
> +  }
Else is redundant, do it like this
return ...
}

const vote ....

2022-12-18 09:26 UTC, 8o8inCodes approved these changes

2022-12-18 09:26 UTC, merged