Add posts data to backend and receive posts at the frontend.
VicDosya/react-post pull request #2
Opened 2022-11-23 15:48 UTC by VicDosya

Added few CSS touches to space out the content.

2022-11-23 18:43 UTC, 8o8inCodes requested changes

2022-11-23 18:43 UTC, 8o8inCodes commented on client/src/Components/PostPage.js
> +    }
Don't use ref for controlling the values. There is a much easier way:

```jsx
const MyComponent = () => {
  const [title, setTitle] = useState('');

  return (
    <div className={s.container}>
      <input
        type="text"
        value={title}
        onChange={e => setTitle(e.target.value)}
        placeholder="Enter title"
      />
    </div>
  );
};
```

2022-11-24 13:05 UTC, VicDosya commented on client/src/Components/PostPage.js
> +    }
Good point

2022-11-24 13:14 UTC, VicDosya commented
![image](https://user-images.githubusercontent.com/96661032/203793129-6880d3ba-364f-4bf8-8d18-7a3e01353f43.png)

2022-11-24 13:26 UTC, 8o8inCodes approved these changes

2022-11-24 13:30 UTC, merged