Login mech
VicDosya/react-post pull request #9
Opened 2022-12-05 11:05 UTC by VicDosya

2022-12-05 18:15 UTC, VicDosya commented
![image](https://user-images.githubusercontent.com/96661032/205711484-b5691a69-4914-4678-963d-faeab9c4b48c.png)

2022-12-06 18:40 UTC, 8o8inCodes requested changes

2022-12-06 18:40 UTC, 8o8inCodes commented on client/src/Components/Login.js
> +      setStatus(res.data.status);
In both cases you're setting the status with the res.data.status

So why not do something like this:

```js
setStatus(res.data.status)
if(!res.data.error){
      setEmail("");
      setPassword("");
      setTimeout(goHomePage, 2000);
}
```

2022-12-06 18:40 UTC, 8o8inCodes commented on client/src/Components/Register.js
> +    }
Same here

2022-12-07 10:34 UTC, merged